name: daeawt
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flutter_share: ^2.0.0
  package_info_plus: ^3.0.2
  change_app_package_name: ^1.1.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  in_app_review: ^2.0.6
  shared_preferences: ^2.1.0
  easy_localization: ^3.0.1
  pin_code_fields: ^8.0.1
  url_launcher: ^6.1.11
  persistent_bottom_nav_bar: ^5.0.2
  contacts_service: ^0.6.3
  get_it: ^7.2.0
  get: ^4.6.5
  cached_network_image: ^3.2.3
  flutter_launcher_icons: ^0.12.0
  permission_handler: ^10.4.2
  email_validator: ^2.1.17
  connectivity_plus: ^3.0.6
  internet_connection_checker: ^1.0.0+1
  fluttertoast: ^8.2.1
  flutter_phoenix: ^1.1.1
  flutter_windowmanager: ^0.2.0
  image_picker:
  google_maps_flutter:
  geocoding:
  firebase_core:
  firebase_auth:
  google_sign_in:
  geolocator: ^8.2.0
  dropdown_button2: ^2.1.3
  flutter_svg:
  device_preview:



dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/splash_center_logo.jpg"
  adaptive_icon_foreground: "assets/images/splash_center_logo.jpg"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  fonts:
   - family: Cairo
     fonts:
       - asset: assets/fonts/Cairo-Black.ttf
       - asset: assets/fonts/Cairo-Bold.ttf
       - asset: assets/fonts/Cairo-ExtraBold.ttf
       - asset: assets/fonts/Cairo-ExtraLight.ttf
       - asset: assets/fonts/Cairo-Light.ttf
       - asset: assets/fonts/Cairo-Medium.ttf
       - asset: assets/fonts/Cairo-Regular.ttf
       - asset: assets/fonts/Cairo-SemiBold.ttf
       - asset: assets/fonts/font_bold.ttf
       - asset: assets/fonts/font_normal.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
